const PValues = {
  ppr: {
    adpKey: 'adp',
    valueKey: 'value',
    rankKey: 'rank',
    redraftRank: 'redraft_rank',
    rank: 'rank',
    buyIndex: 'buy_index',
    winNowIndex: 'win_now_index',
    trend: 'trend',
    buyindex: 'buyindex',
    win_now: 'win_now',
    redraft: 'redraft',
    rookie: 'rookie',
    e1Rankings: 'e1',
    e2Rankings: 'e2',
    e3Rankings: 'e3',
    e4Rankings: 'e4',
    e5Rankings: 'e5',
    e6Rankings: 'e6',
    e7Rankings: 'e7',
    e8Rankings: 'e8',
    e9Rankings: 'e9',
    e10Rankings: 'e10',
    e11Rankings: 'e11',
    e12Rankings: 'e12',
    e13Rankings: 'e13',
    e14Rankings: 'e14',
    e15Rankings: 'e15',
    e16Rankings: 'e16',
  },
  super: {
    adpKey: 'adp_2qb',
    valueKey: 'value_2qb',
    rankKey: 'rank_2qb',
    redraftRank: 'redraft_rank_2qb',
    rank: 'rank_2qb',
    buyIndex: 'buy_index_2qb',
    winNowIndex: 'win_now_index_2qb',
    trend: 'trend_2qb',
    buyindex: 'buyindex_2qb',
    win_now: 'win_now_2qb',
    redraft: 'redraft_2qb',
    rookie: 'rookie_2qb',
  },
};

export default PValues;
