const PValues = {
    ppr: {
      past6MonthsValue: [
        'may_16_value',
        'jun_16_value',
        'jul_16_value',
        'aug_16_value',
        'sept_16_value',
        'oct_16_value',
      ],
      past6MonthsADP: [
        'may_16',
        'jun_16',
        'jul_16',
        'aug_16',
        'sept_16',
        'oct_16',
      ],
      chartLabels: [
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sept',
        'Oct',
      ],
      redraftRank: 'redraft_rank',
      rank: 'rank',
      buyIndex: 'buy_index',
      winNowIndex: 'win_now_index',
      trend: 'trend',
  },
  super: {
    past6MonthsValue: [
      'may_16_value_2qb',
      'jun_16_value_2qb',
      'jul_16_value_2qb',
      'aug_16_value_2qb',
      'sept_16_value_2qb',
      'oct_16_value_2qb',
    ],
    past6MonthsADP: [
      'may_16_2qb',
      'jun_16_2qb',
      'jul_16_2qb',
      'aug_16_2qb',
      'sept_16_2qb',
      'oct_16_2qb',
    ],
    chartLabels: [
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sept',
      'Oct',
    ],
    redraftRank: 'redraft_rank_2qb',
    rank: 'rank_2qb',
    buyIndex: 'buy_index_2qb',
    winNowIndex: 'win_now_index_2qb',
    trend: 'trend_2qb',
  },
};

export default PValues;
