const PValues = {
    ppr: {
      past6MonthsValue: [
        'feb_16_value',
        'mar_16_value',
        'apr_16_value',
        'may_16_value',
        'jun_16_value',
        'jul_16_value',
      ],
      past6MonthsADP: [
        'feb_16',
        'mar_16',
        'apr_16',
        'may_16',
        'jun_16',
        'jul_16',
      ],
      chartLabels: [
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
      ],
      redraftRank: 'redraft_rank',
      rank: 'rank',
      buyIndex: 'buy_index',
      winNowIndex: 'win_now_index',
      trend: 'trend',
  },
  super: {
    past6MonthsValue: [
      'feb_16_value_2qb',
      'mar_16_value_2qb',
      'apr_16_value_2qb',
      'may_16_value_2qb',
      'jun_16_value_2qb',
      'jul_16_value_2qb',
    ],
    past6MonthsADP: [
      'feb_16_2qb',
      'mar_16_2qb',
      'apr_16_2qb',
      'may_16_2qb',
      'jun_16_2qb',
      'jul_16_2qb',
    ],
    chartLabels: [
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
    ],
    redraftRank: 'redraft_rank_2qb',
    rank: 'rank_2qb',
    buyIndex: 'buy_index_2qb',
    winNowIndex: 'win_now_index_2qb',
    trend: 'trend_2qb',
  },
}

export default PValues;
